apiVersion: v1
kind: PersistentVolume
metadata:
  name: reg-pv
  namespace: apps
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /home/devops/devops/registry/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reg-pvc
  namespace: apps
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
