apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: apps
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:8.0
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: toor89
        - name: MYSQL_DATABASE
          value: "LIFEDB"
        - name: MYSQL_USER
          value: "devops"
        - name: MYSQL_PASSWORD
          value: "toor89" 

        ports:
        - containerPort: 3306
          name: mysql

          
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc

      nodeSelector:
         super: kolobok
      tolerations:
              - key: node-role.kubernetes.io/master
                effect: NoSchedule
     
---


apiVersion: v1
kind: Service
metadata:
  name: mysqlexpose
  namespace: apps
spec:
  type: LoadBalancer
  selector:
     app: mysql

  ports:
    - name: http
      protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 32306
  externalIPs:
     - 192.168.2.25


