
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: apps
spec:
  capacity:
    storage: 15Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/home/devops/devops/database/data"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: apps
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi




